# Generated by Django 5.2.1 on 2025-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'Pix (Manual)')], default='pix', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=50),
        ),
    ]
